"""initial schema

Revision ID: 8e0d66904799
Revises: 
Create Date: 2026-07-03 09:10:17.161255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.guid

# revision identifiers, used by Alembic.
revision: str = '8e0d66904799'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('examens',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('type_examen', sa.Enum('CEP', 'BEPC', 'BAC', 'CONCOURS_DIRECT', name='type_examen'), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='statut_examen'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_examens_statut_annee', 'examens', ['statut', 'annee'], unique=False)
    op.create_table('ingestions',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('examen_id', app.models.guid.GUID(), nullable=False),
    sa.Column('admin_id', app.models.guid.GUID(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('type_fichier', sa.Enum('PDF', 'EXCEL', 'PDF_OCR', name='type_fichier'), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PREVISUALISATION', 'VALIDEE', 'PUBLIEE', 'REJETEE', name='statut_ingestion'), nullable=False),
    sa.Column('nombre_lignes_detectees', sa.Integer(), nullable=False),
    sa.Column('nombre_erreurs', sa.Integer(), nullable=False),
    sa.Column('publiee_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['examen_id'], ['examens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_preinscription',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('examen_id', app.models.guid.GUID(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('numero_pv', sa.String(length=50), nullable=False),
    sa.Column('consentement', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ENVOYE', 'ECHEC', name='statut_notification'), nullable=False),
    sa.Column('envoye_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_examen_statut', 'notifications_preinscription', ['examen_id', 'statut'], unique=False)
    op.create_table('resultats',
    sa.Column('id', app.models.guid.GUID(), nullable=False),
    sa.Column('examen_id', app.models.guid.GUID(), nullable=False),
    sa.Column('ingestion_id', app.models.guid.GUID(), nullable=False),
    sa.Column('numero_pv', sa.String(length=50), nullable=False),
    sa.Column('jury', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=255), nullable=True),
    sa.Column('etablissement', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('moyenne', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('donnees_brutes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resultats_examen_pv_jury', 'resultats', ['examen_id', 'numero_pv', 'jury'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resultats_examen_pv_jury', table_name='resultats')
    op.drop_table('resultats')
    op.drop_index('ix_notifications_examen_statut', table_name='notifications_preinscription')
    op.drop_table('notifications_preinscription')
    op.drop_table('ingestions')
    op.drop_index('ix_examens_statut_annee', table_name='examens')
    op.drop_table('examens')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
    # Autogenerate drops the tables but not the PostgreSQL enum types sa.Enum created
    # implicitly: without this, `downgrade base` then `upgrade head` fails with
    # "type ... already exists" (caught by the backend CI migration job).
    bind = op.get_bind()
    for nom_type in (
        'statut_notification',
        'statut_ingestion',
        'type_fichier',
        'statut_examen',
        'type_examen',
    ):
        postgresql.ENUM(name=nom_type).drop(bind, checkfirst=True)
