"""add fonction publique fields to resultats

Revision ID: c7e2a4f91d05
Revises: a3f8c1d92b47
Create Date: 2026-07-04 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c7e2a4f91d05'
down_revision: Union[str, None] = 'a3f8c1d92b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultats', sa.Column('numero_recepisse', sa.String(length=20), nullable=True))
    op.add_column('resultats', sa.Column('code_concours', sa.String(length=10), nullable=True))
    op.add_column('resultats', sa.Column('code_centre', sa.String(length=10), nullable=True))
    op.add_column('resultats', sa.Column('rang_numerique', sa.Integer(), nullable=True))
    op.add_column('resultats', sa.Column('rang_affiche', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultats', 'rang_affiche')
    op.drop_column('resultats', 'rang_numerique')
    op.drop_column('resultats', 'code_centre')
    op.drop_column('resultats', 'code_concours')
    op.drop_column('resultats', 'numero_recepisse')
    # ### end Alembic commands ###
