"""add numero_cnib to resultats

Revision ID: 1bbc06f0b26a
Revises: e1d1a79646c2
Create Date: 2026-07-03 14:50:42.685679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbc06f0b26a'
down_revision: Union[str, None] = 'e1d1a79646c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultats', sa.Column('numero_cnib', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultats', 'numero_cnib')
    # ### end Alembic commands ###
