"""add erreurs_fichier to ingestions

Revision ID: a3f8c1d92b47
Revises: 1bbc06f0b26a
Create Date: 2026-07-04 06:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3f8c1d92b47'
down_revision: Union[str, None] = '1bbc06f0b26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ingestions',
        sa.Column(
            'erreurs_fichier',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default='[]',
        ),
    )
    op.alter_column('ingestions', 'erreurs_fichier', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestions', 'erreurs_fichier')
    # ### end Alembic commands ###
