"""add ingestion preview data

Revision ID: e1d1a79646c2
Revises: 8e0d66904799
Create Date: 2026-07-03 09:31:33.332376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d1a79646c2'
down_revision: Union[str, None] = '8e0d66904799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ingestions',
        sa.Column(
            'apercu_donnees',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default='[]',
        ),
    )
    op.alter_column('ingestions', 'apercu_donnees', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestions', 'apercu_donnees')
    # ### end Alembic commands ###
